apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
  annotations:
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/e-varejo/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000            